"""Add challenge fields to ChoreCompletion

Revision ID: b78e8e2c6498
Revises: 
Create Date: 2025-04-19 01:18:25.772856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78e8e2c6498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('challenged_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('challenge_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('challenge_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('challenge_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('defense', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['challenged_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_completions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('defense')
        batch_op.drop_column('challenge_status')
        batch_op.drop_column('challenge_date')
        batch_op.drop_column('challenge_reason')
        batch_op.drop_column('challenged_by')
        batch_op.drop_column('challenged')

    # ### end Alembic commands ###
